apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-mediawiki
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-mediawiki
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mediawiki-configmap
              key: mysql_user
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: mysql_database
              name: mediawiki-configmap
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: secret-mediawiki
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /etc/mysql/conf.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc