apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - ./namespace.yaml

namespace: qa
namePrefix: qa-

configMapGenerator:
  - name: mediawiki-configmap
    literals:
      - "mysql_host=qa-mysql-svc.qa.svc.cluster.local"
      - "mysql_database=mediawik"
      - "mysql_user=mediawik"


patchesStrategicMerge:
  - mediawiki-application/deployment.yaml
