apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium-retain
  resources:
    requests:
      storage: 5Gi