apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - ./namespace.yaml

namespace: dev
namePrefix: dev-

configMapGenerator:
  - name: mediawiki-configmap
    literals:
      - "mysql_host=dev-mysql-svc.dev.svc.cluster.local"
      - "mysql_database=mediawik"
      - "mysql_user=mediawik"

patchesStrategicMerge:
  - mediawiki-application/deployment.yaml
